add frontend checks
AsPulse/dtm-database pull request #9
Opened 2023-09-14 16:00 UTC by hulk510

- setup frontend checks
-  https://github.com/AsPulse/dtm-database/issues/5

2023-09-14 16:45 UTC, Mogyuchi requested changes

2023-09-14 16:45 UTC, Mogyuchi commented on .github/workflows/frontend-checks.yml
> +          fetch-depth: 0
んーと。
https://github.com/actions/checkout/tree/3df4ab11eba7bda6032a0b82a6bb43b11571feac?tab=readme-ov-file#fetch-all-history-for-all-tags-and-branches

2023-09-14 16:58 UTC, hulk510 commented on .github/workflows/frontend-checks.yml
> +          fetch-depth: 0
> Fetch all history for all tags and branches

俺の脳内では1にしてるイメージやったわ、デフォルトで1なんやな消しときます。

2023-09-14 23:43 UTC, AsPulse requested changes
fmtとlint分けてほしい！
どっちのチェックが落ちたのか分かりづらくなるから…… ( #8 みたいな感じで複数jobを生やせばおｋ )

2023-09-15 00:16 UTC, hulk510 commented on .github/workflows/frontend-checks.yml
> +          fetch-depth: 0
消しzumi

2023-09-15 00:17 UTC, hulk510 commented
ありがとうございますー
workflowわけておきました

2023-09-15 01:27 UTC, AsPulse approved these changes
**LGTM!**
<img alt="" src="https://github.com/AsPulse/dtm-database/assets/84216737/059a9179-56ac-44c1-b5c4-3b2edf843955" width="300">

2023-09-17 00:00 UTC, haruki7049 approved these changes
LGTM.

2023-09-17 02:29 UTC, Mogyuchi requested changes

2023-09-17 02:29 UTC, Mogyuchi commented on .github/workflows/frontend-checks.yml
> +          version: 8
このプロジェクトでは
https://github.com/AsPulse/dtm-database/blob/7b310f7b71af2f67b36e7398dc252a05b4d05715/dtm-database-frontend/package.json#L15
が指定されているため、version指定は不要です。
https://github.com/pnpm/action-setup/tree/d882d12c64e032187b2edb46d3a0d003b7a43598?tab=readme-ov-file#version

（管理しなくてはならない箇所は少ないほど良いのでここでの指定はしないべきです）

2023-09-17 02:29 UTC, Mogyuchi commented on .github/workflows/frontend-checks.yml
permissions を指定しよう！
https://docs.github.com/ja/actions/using-jobs/assigning-permissions-to-jobs

2023-09-17 03:36 UTC, AsPulse commented on .github/workflows/frontend-checks.yml
これ知らなかった……
`backend-checks.yml`の方もpermission指定したほうがいいのかな？

2023-09-17 03:40 UTC, hulk510 commented on .github/workflows/frontend-checks.yml
> +          version: 8
version指定しないとci落ちてたから追加したけど、package.jsonのファイル指定できそうなのでそっちで修正してみますー

2023-09-17 04:43 UTC, Mogyuchi commented on .github/workflows/frontend-checks.yml
> +          version: 8
> version指定しないとci落ちてたから追加したけど
あーたしかにデフォルトだとrootのを見てそう

2023-09-17 04:47 UTC, hulk510 commented
修正点
- pnpmのinstallはpackage.jsonのファイルを参照するように変更
- パーミッションの追加

パーミションは今の所どれもいらなそうなので一旦全部なしにした。

2023-09-17 04:55 UTC, Mogyuchi commented on .github/workflows/frontend-checks.yml
したほうが良いな。
https://docs.github.com/ja/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

2023-09-17 05:06 UTC, Mogyuchi approved these changes

2023-09-17 09:12 UTC, merged